path:
  hubert_ckpt: utils/hubert_extraction/mhubert_base_vp_en_es_fr_it3.pt
  km_path: utils/hubert_extraction/mhubert_base_vp_en_es_fr_it3_L11_km1000.bin
  root_dir: runs/hubert_extraction
  dataset_dir: /media/newhddd/SpeechDatasets/TTS/syspin/files_16000 # Folder containing all speakers. each speaker contains wavs and txt folder