path:
  wav_path: "/media/newhd/Neil/LJSpeech-1.1/wavs_16khz"
  root_path: "runs/LJSpeech"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  alignment_path: "runs/LJSpeech/alignment"
  hubert_path: "runs/LJSpeech/hb_fs2.txt"

preprocess:
  val_size: 100
  hubert_codes: 100
  language: "en"
  speaker: "single" # 'parent_name' or 'parent_parent_name' or '_' or 'single'
