optimizer:
  init_lr: 0.0001
  betas: [0.9, 0.98]
  weight_decay: 0.0

train: 
  warmup_steps: 2000
  total_steps: 50000
  log_every: 10
  val_every: 1000
  save_every: 1000
  batch_size: 12
  grad_acc_steps: 4
  grad_clip: 1.0

path:
  ckpt_path: "runs/LJSpeech/ckpt"
  log_path: "runs/LJSpeech/logs"

